apiVersion: apps/v1
kind: Deployment
metadata:
  name: depi-app
  namespace: depi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: depi-app
  template:
    metadata:
      labels:
        app: depi-app
    spec:
      containers:
        - name: depi-container
          image: abeerseada/flask-app-1:39
          imagePullPolicy: Always
          ports:
            - containerPort: 5051
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: FLASK_ENV
              value: development
            - name: FLASK_APP
              value: app.py
          command: ["python", "app.py"]
