apiVersion: v1
kind: Service
metadata:
  name: depi-service
  namespace: depi
spec:
  type: NodePort
  selector:
    app: depi-app
  ports:
    - port: 5051
      targetPort: 5051
      nodePort: 30008
