services:
  web:
    build: .
    container_name: depi-flask-web
    env_file:
      - ./.env
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
    ports:
      - "5051:5051"
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - static_vol:/app/static
    networks:
      - depi-net

  mongo:
    image: mongo:6
    container_name: depi-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - depi-net

volumes:
  mongo_data:
  static_vol:

networks:
  depi-net:
    driver: bridge
