global:
  resolve_timeout: 5m 

route:
  receiver: "slack_notifications"
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m

receivers:
  - name: "slack_notifications"
    slack_configs:
      - api_url: "${SLACK_WEBHOOK_URL}"
        channel: "#alerts"
        username: "PrometheusAlert"
