global:
  resolve_timeout: 5m 

route:
  receiver: "slack_notifications"
  group_wait: 30s         # Waiting time to send first alert 
  group_interval: 1m      # time to wait between sending notifications for the same group
  repeat_interval: 1m     # repeat notification if alert still fires 

receivers:
  - name: "slack_notifications"
    slack_configs:
      - api_url: "${SLACK_WEBHOOK_URL}"
        channel: "#alerts"
        username: "PrometheusAlert"