global:
  scrape_interval: 15s

rule_files: 
  - "/etc/prometheus/rules/alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jenkins-master-node'
    static_configs:
      - targets:
          - '10.0.1.51:9100'

  - job_name: 'jenkins-slave-node'
    static_configs:
      - targets:
          - '10.0.10.137:9100'

  - job_name: 'jenkins-master'
    metrics_path: /prometheus
    static_configs:
      - targets:
          - '10.0.1.51:8080'
